dependency-dir: ../lib

depends:
    - crc
    - parameter
    - nanopb
    - pid
    - arm-cortex-tools
    - timestamp
    - msgbus
    - lwip
    - fatfs
    - error
    - goap
    - quadramp
    - aversive
    - chibios-syscalls
    - trace

target.arm:
    - src/main.c
    - src/adafruit_display_driver/gdisp_lld_hx8357.c
    - src/adafruit_display_driver/board_hx8357.c
    - src/debug/panic_log.c
    - src/debug/log.c
    - src/debug/blocking_uart.c
    - src/lwip_bindings/lwipthread.c
    - src/lwip_bindings/arch/sys_arch.c
    - src/commands.cpp
    - src/config.c
    - src/can/uavcan_node.cpp
    - src/can/motor_driver.c
    - src/can/motor_driver_uavcan.cpp
    - src/can/motor_manager.c
    - src/can/motor_feedback_streams_handler.cpp
    - src/can/beacon_signal_handler.cpp
    - src/can/emergency_stop_handler.cpp
    - src/can/can_io_driver.cpp
    - src/can/sensor_handler.cpp
    - src/can/uwb_position_handler.cpp
    - src/can/can_uwb_ip_netif.cpp
    - src/can/electron_starter.cpp
    - src/usbconf.c
    - src/base/rs_port.c
    - src/base/cs_port.c
    - src/base/encoder.c
    - src/gui.cpp
    - src/gui/Menu.cpp
    - src/gui/MenuPage.cpp
    - src/base/base_controller.c
    - src/base/map_server.cpp
    - src/robot_helpers/motor_helpers.c
    - src/robot_helpers/arm_helpers.cpp
    - src/trace/trace_points.c
    - src/trace/trace_port.c
    - src/strategy.cpp
    - src/filesystem.c
    - src/http/server.c
    - src/control_panel.c
    - src/pca9685_pwm.c
    - src/parameter_port.c
    - src/strategy/score_counter.cpp
    - src/udp_topic_broadcaster.c
    - src/manipulator/hw.cpp
    - src/manipulator/gripper.cpp
    - src/manipulator/manipulator_thread.cpp
    - src/uid.c
    - src/strategy_impl/actions.cpp
    - src/strategy_impl/base.cpp
    - src/strategy_impl/simulation.cpp
    - src/ally_position_service.c

source:
    - src/unix_timestamp.c
    - src/can/bus_enumerator.c
    - src/math/lie_groups.c
    - src/base/map.c
    - src/robot_helpers/math_helpers.c
    - src/robot_helpers/beacon_helpers.c
    - src/robot_helpers/trajectory_helpers.c
    - src/robot_helpers/strategy_helpers.c
    - src/base/base_helpers.c
    - src/strategy/state.cpp
    - src/strategy/score.cpp
    - src/msgbus_protobuf.c
    - src/manipulator/scara_kinematics.c
    - src/manipulator/kinematics.cpp
    - src/manipulator/state_estimator.cpp
    - src/manipulator/controller.cpp

include_directories:
    - src/
    - src/lwip_bindings
    - src/adafruit_display_driver/
    - src/board/
    - src/debug/
    - src/can/
    - src/comm/
    - ../lib/eigen/
    - build # This is where generated protobuf code goes

tests:
    - tests/ch.cpp
    - tests/unix-timestamp.cpp
    - tests/bus_enumerator.cpp
    - tests/test_map.cpp
    - tests/test_math_helpers.cpp
    - tests/test_beacon_helpers.cpp
    - tests/test_trajectory_helpers.cpp
    - tests/obstacle_avoidance.cpp
    - tests/trajectory_manager_test.cpp
    - tests/test_scara_kinematics.cpp
    - tests/lie_groups.cpp
    - tests/test_base_helpers.cpp
    - tests/test_strategy_helpers.cpp
    - tests/test_strategy.cpp
    - tests/strategy/test_score.cpp
    - tests/strategy/test_state.cpp
    - tests/msgbus_protobuf.cpp
    - tests/test_3dof_pendulum_kinematics.cpp
    - tests/test_manipulator_control.cpp
    - tests/test_arm_pathfinding.cpp

templates:
    app_src.mk.jinja: app_src.mk
    CMakeLists.txt.jinja: CMakeLists.txt
