dependency-dir: ../lib

depends:
    - crc
    - serial-datagram:
        fork: Stapelzeiger
    - parameter:
        fork: Stapelzeiger
    - simplerpc
    - pid
    - arm-cortex-tools
    - timestamp
    - msgbus

target.arm:
    - src/main.c
    - src/debug/panic_log.c
    - src/debug/blocking_uart.c
    - src/sntp/sntp.c
    - src/commands.c
    - src/comm/rpc_server.c
    - src/comm/rpc_callbacks.c
    - src/comm/msg_callbacks.c
    - src/comm/stream.c
    - src/config.c
    - src/can/uavcan_node.cpp
    - src/can/motor_driver.c
    - src/can/motor_driver_uavcan.cpp
    - src/can/motor_manager.c
    - src/malloc_lock.c
    - src/usbconf.c
    - src/aversive_port/cvra_motors.c
    - src/aversive_port/cvra_pid.c
    - src/base/encoder.c
    - src/base/base_controller.c
    - src/config_msgpack.c
    - src/trace/trace_points.c
    - src/robot_helpers/strategy_helpers.c
    - src/strategy.c

source:
    - src/unix_timestamp.c
    - src/can/bus_enumerator.c
    - src/trajectories.c
    - src/trace/trace.c
    - src/robot_helpers/math_helpers.c
    - src/robot_helpers/trajectory_helpers.c
    - src/aversive/error/error.c
    - src/aversive/quadramp/quadramp.c
    - src/aversive/robot_system/angle_distance.c
    - src/aversive/robot_system/robot_system.c
    - src/aversive/control_system_manager/control_system_manager.c
    - src/aversive/position_manager/position_manager.c
    - src/aversive/trajectory_manager/trajectory_manager.c
    - src/aversive/trajectory_manager/trajectory_manager_core.c
    - src/aversive/trajectory_manager/trajectory_manager_utils.c
    - src/aversive/blocking_detection_manager/blocking_detection_manager.c
    - src/aversive/obstacle_avoidance/obstacle_avoidance.c
    - src/aversive/math/geometry/circles.c
    - src/aversive/math/geometry/lines.c
    - src/aversive/math/geometry/polygon.c
    - src/aversive/math/geometry/vect_base.c
    - src/aversive/math/vect2/vect2.c
    - src/aversive/robot_system/angle_distance.c
    - src/aversive/error/error.c
    - src/aversive/robot_system/robot_system.c
    - src/aversive/quadramp/quadramp.c
    - src/aversive/control_system_manager/control_system_manager.c
    - src/aversive/position_manager/position_manager.c
    - src/aversive/trajectory_manager/trajectory_manager.c
    - src/aversive/trajectory_manager/trajectory_manager_core.c
    - src/aversive/trajectory_manager/trajectory_manager_utils.c

include_directories:
    - src/
    - src/aversive/
    - src/board/
    - src/debug/
    - src/can/
    - src/comm/

tests:
    - tests/ch.cpp
    - tests/unix-timestamp.cpp
    - tests/bus_enumerator.cpp
    - tests/trajectories_test.cpp
    - tests/test_math_helpers.cpp
    - tests/test_trajectory_helpers.cpp
    - tests/obstacle_avoidance.cpp
    - src/trace/tests/trace_test.cpp
    - src/trace/tests/trace_points.c
    - tests/trajectory_manager_test.cpp
    - tests/error.cpp

templates:
    app_src.mk.jinja: app_src.mk
    CMakeLists.txt.jinja: CMakeLists.txt
