dependency-dir: ./src/

depends:
    - crc
    - serial-datagram:
        fork: Stapelzeiger
    - parameter:
        fork: Stapelzeiger
    - simplerpc
    - odometry
    - tracy-the-trajectory-tracker
    - pid


target.arm:
    - src/main.c
    - src/panic_log.c
    - src/sntp/sntp.c
    - src/commands.c
    - src/board/board.c
    - src/rpc_server.c
    - src/rpc_callbacks.c
    - src/msg_callbacks.c
    - src/uavcan_node.cpp
    - src/blocking_uart_driver.c
    - src/config.c
    - src/interface_panel.c
    - src/robot_pose.c
    - src/odometry_publisher.c
    - src/motor_driver.c
    - src/motor_driver_uavcan.cpp
    - src/motor_manager.c
    - src/differential_base.c
    - src/stream.c
    - src/fault_debug.c
    - src/node_tracker.c
    - src/malloc_lock.c
    - src/waypoints.c
    - src/log.c
    - src/imu.c

source:
    - src/unix_timestamp.c
    - src/bus_enumerator.c
    - src/trajectories.c

include_directories:
    - src/
    - src/board/

tests:
    - tests/unix-timestamp.cpp
    - tests/bus_enumerator.cpp
    - tests/trajectories_test.cpp
    - tests/log.c

templates:
    app_src.mk.jinja: app_src.mk
