
LIBUAVCAN_STM32_DIR = src/can-driver

LIBUAVCAN_STM32_SRC  = $(LIBUAVCAN_STM32_DIR)/src/uc_stm32_can.cpp
LIBUAVCAN_STM32_SRC += $(LIBUAVCAN_STM32_DIR)/src/uc_stm32_clock.cpp
LIBUAVCAN_STM32_SRC += $(LIBUAVCAN_STM32_DIR)/src/uc_stm32_thread.cpp

LIBUAVCAN_STM32_INC := $(LIBUAVCAN_STM32_DIR)/include/
