#ifndef SHELLCONF_H
#define SHELLCONF_H

/* Shell related config */
#define SHELL_MAX_ARGUMENTS 5
#define SHELL_MAX_LINE_LENGTH 100
#define SHELL_USE_HISTORY TRUE
#define SHELL_USE_ESC_SEQ TRUE
#define SHELL_MAX_HIST_BUFF 4 * SHELL_MAX_LINE_LENGTH

#define SHELL_CMD_THREADS_ENABLED FALSE
#define SHELL_CMD_TEST_ENABLED FALSE

#endif /* SHELLCONF_H */
