#ifndef UDP_TOPIC_INJECTOR_H
#define UDP_TOPIC_INJECTOR_H

#ifdef __cplusplus
extern "C" {
#endif

/** Starts the UDP topic injector thread.
 *
 * This thread listens for incoming packets on port 10000. They are formatted
 * as the outcoming packets from this board (see udp_topic_broadcaster.c).
 * Those packets then get injected in the local messagebus as if they were
 * generated by a local thread.
 *
 * This can be used for hardware in the loop testing, or to test some control
 * code running on a PC as it it was running locally.
 *
 * @note This injector will not create topics. If a message arrives for a non
 * existing topic, it will be silently dropped.
 */
void udp_topic_injector_start(void);

#ifdef __cplusplus
}
#endif

#endif
