#ifndef ROBOT_PARAMETERS_H
#define ROBOT_PARAMETERS_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Robot base parameters
 */
#define DEBRA_RIGHT_EXTERNAL_WHEEL_RADIUS   0.016f
#define DEBRA_LEFT_EXTERNAL_WHEEL_RADIUS    0.016f
#define DEBRA_RIGHT_MOTOR_WHEEL_RADIUS      0.030f
#define DEBRA_LEFT_MOTOR_WHEEL_RADIUS       0.030f
#define DEBRA_RIGHT_WHEEL_DIRECTION         -1
#define DEBRA_LEFT_WHEEL_DIRECTION          1
#define DEBRA_EXTERNAL_WHEELBASE            0.194f
#define DEBRA_MOTOR_WHEELBASE               0.156f

#define NASTYA_RIGHT_EXTERNAL_WHEEL_RADIUS  0.016f
#define NASTYA_LEFT_EXTERNAL_WHEEL_RADIUS   0.016f
#define NASTYA_RIGHT_MOTOR_WHEEL_RADIUS     0.030f
#define NASTYA_LEFT_MOTOR_WHEEL_RADIUS      0.030f
#define NASTYA_RIGHT_WHEEL_DIRECTION        1
#define NASTYA_LEFT_WHEEL_DIRECTION         -1
#define NASTYA_EXTERNAL_WHEELBASE           0.194f
#define NASTYA_MOTOR_WHEELBASE              0.156f

#ifdef DEBRA
#define ROBOT_RIGHT_EXTERNAL_WHEEL_RADIUS 	DEBRA_RIGHT_EXTERNAL_WHEEL_RADIUS
#define ROBOT_LEFT_EXTERNAL_WHEEL_RADIUS	DEBRA_LEFT_EXTERNAL_WHEEL_RADIUS
#define ROBOT_RIGHT_MOTOR_WHEEL_RADIUS 	    DEBRA_RIGHT_MOTOR_WHEEL_RADIUS
#define ROBOT_LEFT_MOTOR_WHEEL_RADIUS	    DEBRA_LEFT_MOTOR_WHEEL_RADIUS
#define ROBOT_RIGHT_WHEEL_DIRECTION         DEBRA_RIGHT_WHEEL_DIRECTION
#define ROBOT_LEFT_WHEEL_DIRECTION	        DEBRA_LEFT_WHEEL_DIRECTION
#define ROBOT_EXTERNAL_WHEELBASE 			DEBRA_EXTERNAL_WHEELBASE
#define ROBOT_MOTOR_WHEELBASE 			    DEBRA_MOTOR_WHEELBASE
#else
#error "use debra"
#define ROBOT_RIGHT_EXTERNAL_WHEEL_RADIUS 	NASTYA_RIGHT_EXTERNAL_WHEEL_RADIUS
#define ROBOT_LEFT_EXTERNAL_WHEEL_RADIUS	NASTYA_LEFT_EXTERNAL_WHEEL_RADIUS
#define ROBOT_RIGHT_WHEEL_DIRECTION         NASTYA_RIGHT_WHEEL_DIRECTION
#define ROBOT_LEFT_WHEEL_DIRECTION	        NASTYA_LEFT_WHEEL_DIRECTION
#define ROBOT_EXTERNAL_WHEELBASE 			NASTYA_EXTERNAL_WHEELBASE
#define ROBOT_MOTOR_WHEELBASE 			    NASTYA_MOTOR_WHEELBASE
#endif

#ifdef __cplusplus
}
#endif

#endif /* ROBOT_PARAMETERS_H */
