# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder "salt/roots/", "/srv/salt/"

  config.vm.provision :salt do |salt|
      salt.run_highstate = true
      salt.verbose = false
      salt.install_master = false
      salt.bootstrap_options = '-F -c /tmp/ -P'
      salt.colorize = true
      salt.minion_config = "salt/minion"
  end
end
