MESSAGE(STATUS "Chibios version:" ${ChibiOS_FIND_VERSION_MAJOR})

INCLUDE(ChibiOS/18.2/ChibiOS)

LIST(REMOVE_DUPLICATES ChibiOS_INCLUDE_DIRS)
LIST(REMOVE_DUPLICATES ChibiOS_SOURCES)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ChibiOS DEFAULT_MSG ChibiOS_SOURCES ChibiOS_INCLUDE_DIRS)


