name: Unit tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install prerequisites
      run: |
        sudo apt-get update -y && sudo apt-get install -y freeglut3-dev libgpiod-dev libsdl2-dev protobuf-compiler python python3-pip python3-dev python3-setuptools libcpputest-dev build-essential cmake 
        pip3 install msgpack-python==0.4.8 PyYAML==3.11
        pip3 install --upgrade protobuf
        pushd $GITHUB_WORKSPACE/lib/uavcan/libuavcan/dsdl_compiler/pyuavcan
        sudo python3 setup.py install
        popd
        pushd $GITHUB_WORKSPACE/lib/uavcan/libuavcan/dsdl_compiler/
        sudo python3 setup.py install
        popd
        pushd $GITHUB_WORKSPACE/lib/nanopb/nanopb/generator/
        sed -i 's/env python/env python3/' *.py
        popd
        pushd $GITHUB_WORKSPACE/lib/nanopb/nanopb/generator/proto
        make
        popd
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        mkdir build
        cd build
        cmake ..
        make
    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        make test
